### ISSUE TITLE
Solved: PHP Config Issue - small file upload works, files over 2MB fail

### ISSUE THREAD

**Issue by Ben-CA** [akeeba/s3#11]
I can upload smaller files (200KB) flawlessly, but when I try a file such as a digital camera picture (3MB - still not very big) then I get an error "cannot open for reading" thrown by CannotOpenFileForRead.php Exception.)

I can't see RAM being an issue for a 3MB file (I have 256MB allocated to PHP), AWS server with no production workload.

Here's the portion of code I'm using - works for small files, not for 3MB file for instance.
```
$source_file = $_FILES['file']['tmp_name'];
$input = Input::createFromFile($source_file);
$connector->putObject($input, $document_bucket, $file_with_path);

```
Any ideas what config or such I might have set wrong? I assumed the Multipart shouldn't be required for files of this size, since it's only chunking into 5MB anyways.

**Comment by nikosdion** [comment]
You are getting an exception that is literally called **CannotOpenFileForRead**. What does the _upload method_ or _size_ has to do with anything?! It tells you quite clearly that PHP cannot open the file you specified. The root cause of such a problem typically exists between the keyboard and chair.

**Comment by Ben-CA** [comment]
The thing is, I’ve tried multiple different images, in a normal jpg format. A 200KB jpg image works just fine, while a ~ 2MB or 3MB jpg image fails. 

I don’t care whether PHP can “open” the file - I just want it to upload the bits - which happen to be a jpg image - to S3. 

I’m not saying it’s a problem with the upload method - presumably some configuration - but the only connection I can see between successful uploads and failures is the file size. 

And it’s not like I have a particular corrupt file that causes it.

So I was just hoping someone might have run into this before and have a suggestion.

**Comment by nikosdion** [comment]
> I don’t care whether PHP can “open” the file - I just want it to upload the bits - which happen to be a jpg image - to S3.

So, let me get this straight. You understand that the programming language cannot read the contents of the file. Yet you expect a program running on said language to be able to somehow push these contents which cannot be read onto S3. I will have to assume you are sleep deprived.

> So I was just hoping someone might have run into this before and have a suggestion.

Yes, of course I've run into it! I put the Exception in place because I wasted an hour debugging the library when the problem was that PHP couldn't open the file for reading. The root cause was rather mundane; the file had the wrong access permissions and PHP couldn't read it. That's why I told you that the root cause of this exception is typically between the chair and keyboard.

Again, the _size_ of your file and your _available PHP memory_ are irrelevant to your issue. First and foremost because the problem you get is when opening the file for reading, long before we do anything with S3, as you can see for yourself in this very easy to follow library (printing the exception debug trace would actually show you very plainly how you ended up there). 

Second, I have thousands of sites using this library to send 10MB to 50MB backup archives to S3 using single part uploads (using putObject) through Akeeba Backup for Joomla, Akeeba Backup for WordPress and Akeeba Solo. Not to mention that Ryan who replied to your previous issue is using the same library on JCE which works perfectly fine with large image uploads -- that's literally what he's using it for.

Check why PHP cannot open the file. It's either permissions or you botched the name. Try calling the file foo.jpg and try to do a file_get_contents on it first.

**Comment by Ben-CA** [comment]
So I figured this out, and my problem was that it never occurred to me that AWS would have a default upload_max_filesize parameter in the /etc/php. ini file of ONLY 2MB!

[https://aws.amazon.com/premiumsupport/knowledge-center/wordpress-themes-2mb/](url)

So when I would "upload" a file via a form posting data to the PHP script, the:
`$source_file = $_FILES['file']['tmp_name'];`
Worked fine for files under 2MB. But over that, because the server rejected them because of its default configuration, PHP couldn't open/read them. 

So it wasn't bad permissions or a typo on the filename (and the identical process worked with smaller files) - it was simply the file I thought I had uploaded in fact didn't exist on the server because PHP had blocked the file because it was over 2MB.

(And to clarify, I guess when I think "open" my instinct is like opening a file for display as a user - with the program _understanding its contents_, vs. "reading"/"accessing" the file. And I didn't see why PHP needed to "open" it in regards to understanding the file contents in order to upload it. But yes, it obviously needs to be able to "open" it as far as being able to "read"/"access" the file.)

![image](https://user-images.githubusercontent.com/47060874/83434624-7221e280-a400-11ea-9c7e-55a876fe7ed8.png)

Thanks for your response and further details! Hopefully this will help someone else.

**Comment by Ben-CA** [comment]
Resolved by increasing the upload_max_filesize PHP parameter.

**Comment by nikosdion** [comment]
Again, your problem WAS that PHP cannot read the file... because it never existed on your server! Of course you never told me that you we’re using a form to upload a file but let’s not get massively important details get in the way. After all you still don’t seem to realize how badly you screwed up or what the real problem was – or even the fact that an EC2 instance is just a VM, not a magic unlimited PHP installation. Sigh. 

If you still don’t understand the at least three different ways your code should have caught that problem long before trying to pass invalid bullshit to the library I strongly suggest starting learning the basics of writing software before doing more advanced things like interfacing S3. Otherwise you put yourself and your clients at risk!

Here’s how sane, defensive coding looks like at its absolute bare minimum. First thing you check: is my environment matching my expectations? Second, do I have upload information I can use? Third, does the temporary file PHP uploaded exists and is readable? Fourth, is the file name valid? Fifth, is the MIME type consistent with the file extension and what I need to support? Sixth, is the file data really valid for that MIME type? Then AND ONLY THEN do we start considering using a library to upload it to S3.

**Comment by Ben-CA** [comment]
**Just so you can rest assured, I don't work for Boeing:**
https://www.bloomberg.com/news/articles/2020-02-06/boeing-identifies-new-software-problem-on-grounded-737-max-jet
**Or Sikorsky:**
https://www.verticalmag.com/news/sikorsky-reveals-details-s-97-raider-hard-landing-ntsb-publishes-initial-report/
**Or Tesla:**
https://teslamotorsclub.com/tmc/threads/concerns-with-safety-issues-in-tesla-why-so-many-software-bugs.149898/
**Or Siemens:**
https://www.nydailynews.com/new-york/ny-byford-signal-outage-subway-heat-wave-mta-friday-software-glitch-20190722-5kl5roewvfb57b26x2ujapqlm4-story.html
**Or DFS:**
https://www.dw.com/en/german-air-traffic-software-glitch-one-of-several-problems-afflicting-sector/a-48053507
**Or GE:**
https://www.theregister.com/2004/02/12/software_bug_contributed_to_blackout/

Presumably they all have teams of "experts" - who still make serious software mistakes - and it's much less permissible when there are lives and livelihoods at stake.

Much of my expertise is NOT in the software development space.

We all make mistakes.

**Comment by nikosdion** [comment]
> Much of my expertise is NOT in the software development space.

Therefore my comment about you needing to learn the basics about software development is right on the money.

Also note that you failing to understand the basics is absolutely NOT AT ALL the same thing as a team of engineers failing to catch an edge case in interconnected systems which are at least six orders of magnitude more complex than your trivial code. If you cannot understand that you will never be a software developer.

Start by knowing your limits. Know what you know and what you don't know don't think you know it either.
